services:
  - type: web
    name: circulo-bienes-raices
    runtime: docker
    plan: free
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@circulo.com
      - key: ADMIN_PASSWORD
        value: Admin123!
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: true
