import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
const call=async(path,method='GET',body)=>{const token=localStorage.getItem('token');const r=await fetch(`/api/admin/marketing${path}`,{method,credentials:'include',headers:{...(token?{Authorization:`Bearer ${token}`}:{ }),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo completar');return data;};
const stages=['nuevo','contactado','calificado','visita_agendada','visita_realizada','negociacion','cerrado','perdido'];
export default function AdminMarketing(){
 const [data,setData]=useState(null),[days,setDays]=useState(30),[error,setError]=useState(''),[message,setMessage]=useState(''),[config,setConfig]=useState({}),[url,setUrl]=useState(''),[campaign,setCampaign]=useState({source:'instagram',medium:'organic_social',name:'',content:'video_a'});
 const load=()=>call(`?days=${days}`).then(d=>{setData(d);setConfig(d.config);}).catch(e=>setError(e.message));
 useEffect(()=>{load();},[days]);
 const execute=async(fn)=>{setError('');setMessage('');try{await fn();setMessage('Guardado');await load();}catch(e){setError(e.message);}};
 const field=(key,label)=> <label className="block text-sm">{label}<input className="block w-full bg-white/10 rounded p-2 my-2" value={config[key]||''} onChange={e=>setConfig({...config,[key]:e.target.value})}/></label>;
 let campaignLink='';try{const u=new URL(url);if(u.origin==='https://circulointernacionalveracruz.org'&&/^\/propiedades\/[a-z0-9-]+$/.test(u.pathname)){u.search='';Object.entries({utm_source:campaign.source,utm_medium:campaign.medium,utm_campaign:campaign.name,utm_content:campaign.content}).forEach(([k,v])=>v&&u.searchParams.set(k,v));campaignLink=u.href;}}catch{}
 return <main className="pt-24 min-h-screen bg-[#0a0a0a] text-white"><div className="max-w-6xl mx-auto px-4 pb-20"><Link to="/admin" className="text-amber-400">← Administración</Link><h1 className="text-3xl font-bold my-5">Medición y experimentos</h1><p className="text-gray-400 mb-4">Eventos de navegadores que permitieron medición. Sesiones de esta pestaña, sin identificación entre dispositivos. Clics no equivalen a conversaciones. Los contactos del formulario se registran al ser recibidos.</p>
 <select aria-label="Periodo" className="bg-white/10 p-2 rounded mb-5" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Últimos 7 días</option><option value={30}>Últimos 30 días</option><option value={90}>Últimos 90 días</option></select>{error&&<p role="alert" className="text-red-400 mb-4">{error}</p>}{message&&<p role="status" className="text-green-400 mb-4">{message}</p>}
 <div className="grid sm:grid-cols-3 gap-3 mb-8">{(data?.totals||[]).map(r=><div className="bg-white/5 p-4 rounded-xl" key={r.event}><p className="text-gray-400">{r.event}</p><p className="text-2xl">{r.total}</p><p className="text-xs">{r.sessions} sesiones de pestaña</p></div>)}<div className="bg-white/5 p-4 rounded-xl"><p>Solicitudes recibidas (máximo 100 recientes)</p><p className="text-2xl">{data?.leads?.length||0}</p></div></div>
 <h2 className="text-xl font-semibold mb-3">Canales y campañas</h2><div className="overflow-auto mb-8"><table className="w-full text-sm"><thead><tr>{['Origen','Campaña','Acción','Eventos'].map(t=><th className="text-left p-2" key={t}>{t}</th>)}</tr></thead><tbody>{(data?.sources||[]).map((r,i)=><tr className="border-t border-white/10" key={i}><td className="p-2">{r.source}</td><td>{r.campaign||'Sin identificar'}</td><td>{r.event}</td><td>{r.total}</td></tr>)}</tbody></table></div>
 <h2 className="text-xl font-semibold mb-3">Propiedades</h2><div className="overflow-auto mb-8"><table className="w-full text-sm"><thead><tr><th className="text-left p-2">Propiedad</th><th>Acción</th><th>Eventos</th></tr></thead><tbody>{(data?.properties||[]).map((r,i)=><tr className="border-t border-white/10" key={i}><td className="p-2">{r.title||r.propertyId}</td><td>{r.event}</td><td>{r.total}</td></tr>)}</tbody></table></div>
 <h2 className="text-xl font-semibold mb-3">Solicitudes y CRM</h2><p className="text-gray-400 text-sm mb-3">Conector GHL: {data?.connections?.crmConfigured?'credenciales configuradas; consulta el resultado por solicitud':'pendiente de credenciales en Cloudflare'}. Meta Conversions API: pendiente. La sincronización envía el contacto; inmueble, atribución y etapa permanecen en este tablero hasta configurar campos y pipeline del CRM.</p><div className="overflow-auto mb-8"><table className="w-full text-sm"><thead><tr>{['Nombre / fecha','Origen / inmueble','Etapa','Envío a GHL'].map(t=><th className="text-left p-2" key={t}>{t}</th>)}</tr></thead><tbody>{(data?.leads||[]).map(r=>{const a=JSON.parse(r.attribution||'{}');return <tr className="border-t border-white/10" key={r.id}><td className="p-2">{r.name}<br/>{r.createdAt.slice(0,10)}</td><td>{a.first?.source||'Desconocido'} → {a.latest?.source||a.first?.source||'Desconocido'}<br/>{r.propertyId}<br/>{a.latest?.campaign||a.first?.campaign||''}</td><td><select aria-label={`Etapa de ${r.name}`} className="bg-zinc-800 p-2" value={r.stage} onChange={e=>execute(()=>call('/stage','PUT',{inquiryId:r.id,stage:e.target.value}))}>{stages.map(s=><option key={s}>{s}</option>)}</select></td><td>{r.crmStatus||'pending'} {r.lastError}<br/>{r.crmStatus==='failed'&&<button className="text-amber-400" onClick={()=>execute(()=>call('/retry','POST',{inquiryId:r.id}))}>Reintentar contacto</button>}</td></tr>;})}</tbody></table></div>
 <section className="bg-white/5 rounded-xl p-5 mb-8"><h2 className="text-xl font-semibold mb-3">Conexiones</h2>{field('ga4Id','ID de Google Analytics 4 (G-…)')}{field('metaPixelId','ID del píxel de Meta')}<p className="text-sm text-gray-400">Instalación directa de GA4: desactiva las vistas automáticas por cambios del historial en el flujo de datos para evitar duplicados. No instales además otra etiqueta de GA4 mediante GTM. Los IDs guardados no demuestran recepción: verificar DebugView y Test Events.</p><button className="bg-amber-500 rounded px-4 py-2 mt-3" onClick={()=>execute(()=>call('/config','PUT',config))}>Guardar configuración</button></section>
 <section className="bg-white/5 rounded-xl p-5 mb-8"><h2 className="text-xl font-semibold">Prueba A/B del botón de WhatsApp</h2><p className="text-gray-400 text-sm my-3">A: Consultar por WhatsApp. B: Agenda tu visita por WhatsApp. Asignación aleatoria por pestaña. No determina ganadores ni activa anuncios.</p>{['id','path','hypothesis','reviewDate','budgetLimit'].map(k=><label key={k} className="block text-sm">{{id:'ID único (nuevo por prueba)',path:'Ruta exacta de la propiedad',hypothesis:'Hipótesis',reviewDate:'Fecha de evaluación (AAAA-MM-DD)',budgetLimit:'Límite previsto de gasto; no ejecuta inversión'}[k]}<input className="block w-full bg-white/10 rounded p-2 my-2" value={config.experiment?.[k]||''} onChange={e=>setConfig({...config,experiment:{...config.experiment,[k]:e.target.value}})}/></label>)}<label><input type="checkbox" checked={Boolean(config.experiment?.active)} onChange={e=>setConfig({...config,experiment:{...config.experiment,active:e.target.checked}})}/> Activar prueba</label><button className="block bg-amber-500 rounded px-4 py-2 mt-3" onClick={()=>execute(()=>call('/config','PUT',config))}>Guardar prueba</button><div className="mt-5">{(data?.experiments||[]).map((r,i)=><p key={i}>{r.experiment} · {r.variant} · {r.event}: {r.sessions} sesiones</p>)}</div><p className="text-xs text-gray-400 mt-3">No concluir causalidad comparando canales ni resultados de muestras pequeñas. Esta primera prueba mide clics; la evaluación comercial exige conversaciones y visitas confirmadas.</p></section>
 <section className="bg-white/5 rounded-xl p-5"><h2 className="text-xl font-semibold">Generar enlace de campaña</h2><input aria-label="URL de propiedad" placeholder="URL completa de la propiedad" className="block w-full bg-white/10 rounded p-2 my-3" value={url} onChange={e=>setUrl(e.target.value)}/>{Object.keys(campaign).map(k=><label className="block text-sm" key={k}>{{source:'Red',medium:'Medio',name:'Campaña',content:'Pieza / variante'}[k]}<input className="block w-full bg-white/10 rounded p-2 my-2" value={campaign[k]} onChange={e=>setCampaign({...campaign,[k]:e.target.value})}/></label>)}<textarea aria-label="Enlace identificado" readOnly value={campaignLink} className="w-full h-24 bg-white/10 p-3 rounded"/><p className="text-sm text-gray-400">Copia este enlace al publicar. No se modifican automáticamente publicaciones anteriores.</p></section>
 </div></main>;
}
